FROM python:3.8

LABEL maintainer='sun'

WORKDIR /usr/src/app


COPY ./techtrends/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./techtrends ./


EXPOSE 3111

CMD [ "python", "app.py" ]

